package gui;

import util.Solver;

public class GUI_Tabela  extends javax.swing.JFrame {
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_verdade;
        /**
         * Creates new form telaTabelaVerdade
         */
        public GUI_Tabela() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jScrollPane1 = new javax.swing.JScrollPane();
            tabela_verdade = new javax.swing.JTable();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            tabela_verdade.setAlignmentX(tabela_verdade.CENTER_ALIGNMENT);

            this.geraTabela();
            tabela_verdade.setAutoscrolls(false);
            jScrollPane1.setViewportView(tabela_verdade);
            tabela_verdade.getAccessibleContext().setAccessibleDescription("");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addContainerGap())
            );

            pack();
        }// </editor-fold>

    public void geraTabela(){

        Object[][] resp = new Object[Solver.respostaFinal.length][1];

        for (int i = 0; i < Solver.respostaFinal.length; i++) {
            resp[i][0] = Solver.respostaFinal[i];
        }

        tabela_verdade.setModel(new javax.swing.table.DefaultTableModel(
                resp,
                new String [] {
                        GUI_Argumento.argumento
                }
        ));
    }
}
